### ISSUE TITLE
maintenance mode

### ISSUE THREAD

**Issue by wkloucek** [owncloud/web#10260]
## Is your feature request related to a problem? Please describe.
For a SaaS project we're putting oCIS (backend) into the maintenance mode by answering every request with `HTTP 503` and a html maintenance page as body.

In NGINX this could look like this:

```
        location / {
            return 503;
        }
        error_page 503 @maintenance;
        location @maintenance {
              rewrite ^(.*)$ /index.html break;
        }
```

Currently oC Web doesn't gracefully handle these 503 responses on every API endpoint.
It takes the user a reload of the website to get the maintenance page served. 
It also takes the user a reload to get back from the maintenance page to oC Web.

## Describe the solution you'd like
Have a maintenance mode build into oC Web. If it receives HTTP 503 responses from the backend, it should go into that mode. It could periodically retry and automatically go back to normal mode if maintenance mode is over.

We no longer would have to serve a project specific maintenance page, but could instead just answer all API requests with 503.

It may be nice to load some info-string to display to the user from a well-known endpoint (to be defined I guess)

## Describe alternatives you've considered

Hacks / Workarounds, which don't deserve to be documented in a product's issue tracker.

**Comment by dschmidt** [comment]
If we implement this, we should only do that when a user triggers an action, not on any background tasks. There's little that's more annoying than your page suddenly going into maintenance mode without any interaction

**Comment by kulmann** [comment]
Agreeing with @dschmidt that this can't happen as a "nope, sorry, maintenance" full view port page... imagine you're in a text editor (maybe even without auto save) and your content just goes away without a chance to get it back, just because web discovered that the backend is in maintenance mode. IMO this should be more like a prominent banner, so that you have a chance to copy your content elsewhere (local text file). Needs some more thought.

**Comment by wkloucek** [comment]
> that this can't happen as a "nope, sorry, maintenance" full view port page

Now I get it.

> Needs some more thought.

That would be great! You already brought some cases that I didn't think of and also are definitively not covered with the current project based approach.

For a SaaS, you generally have the problem that you can't inform every user (because you don't have contact details or there are too many).
So when the maintenance mode happens, it should be as non-disruptive to users as possible. This has many aspects like you already explained.

**Comment by jvillafanez** [comment]
Anything to do from the server side? It seems the plan is to let traefik (or nginx or whatever server at the front is being used) handle the issue (basically, returning the 503 code). If this is the case, I think we should document how we expect things to be configured, specially for traefik which is what we're using.
The information is also relevant for QA because they should verify that the web (and other clients) works with the "official" setup, including the maintenance configuration.

So far, the information seems to be focused on web + kubernetes, but there are other environments to be considered.

**Comment by kobergj** [comment]
Good point. @mmattel what do you think? Should we add a subitem to the Maintenance section of the docs? Or is another place better?

**Comment by mmattel** [comment]
> Should we add a subitem to the Maintenance section of the docs?

As discussed, I would do a note in the admin docs and possibly in the dev docs.

**Comment by LukasHirt** [comment]
Should we have E2E tests for this feature? Maybe only on [full-ci] runs? Or only unit tests are sufficient?

**Comment by jvillafanez** [comment]
@LukasHirt in case you aren't aware, it's possible to send content (html pages, images, etc) with the 503 error code. This also affects js code that web might want to get loaded:

![Image](https://github.com/user-attachments/assets/d314153a-12f0-4b33-a02e-39dd480d0b10)

![Image](https://github.com/user-attachments/assets/2e813f98-dfad-4fc5-9fde-4a72738dfd39)

For context, I'm sending a gif with the 503 code.

We can assume that the admins won't be dumb enough to send things that could potentially break the web client, so I don't think it's a security issue, but the fact the browser is trying to do something regardless of the 503 error code is disturbing.

**Comment by LukasHirt** [comment]
> but the fact the browser is trying to do something regardless of the 503 error code is disturbing.

That is due to the difference of expected content, right? If the Web is opened the first time, there is a GET request to display a document (html, etc.) which would correctly show the returned content. But any subsequent request expects json returned. So even though a gif is returned, it is ignored because the request handler does not process that.

**Comment by jvillafanez** [comment]
Yes. If the page is fully refreshed, the 503 content is shown properly

![Image](https://github.com/user-attachments/assets/47aee082-4484-4d77-b9d7-3832b5e3b5a3)

Note that here, the initiator says "document", while above it says "PortalTarget.vue....", which I assume is some kind of loader.

**Comment by jvillafanez** [comment]
For the docker compose + traefik setup, to be considered to be part of the deployment examples, the following changes could be added:
```
services:
  traefik:
    command:
      - "--experimental.plugins.traefik-maintenance.modulename=github.com/TRIMM/traefik-maintenance"
      - "--experimental.plugins.traefik-maintenance.version=v1.0.1"
    volumes:
      - ./config/maintenance/:/maintenance/
    labels:
      - "traefik.http.middlewares.maintenance.plugin.traefik-maintenance.enabled=true"
      - "traefik.http.middlewares.maintenance.plugin.traefik-maintenance.httpResponseCode=503"
      - "traefik.http.middlewares.maintenance.plugin.traefik-maintenance.filename=/maintenance/page.html"
      - "traefik.http.middlewares.maintenance.plugin.traefik-maintenance.triggerFilename=/maintenance/page.html.trigger"
      - "traefik.http.middlewares.maintenance.plugin.traefik-maintenance.httpContentType=text/html; charset=utf-8"

  ocis:
    labels:
      - "traefik.http.routers.ocis.middlewares=maintenance"
```
Those are **added** lines to the default deployment.
* Traefik's command will download the "traefik-maintenance" plugin and install it in the container.
* The new traefik's labels will configure the plugin (more on this below)
* New volume might or might not be needed
* ocis' label will use the configure maintenance plugin.

`filename`, `triggerFilename` and `httpContentType` can be adjusted at will. For example:
```
      - "traefik.http.middlewares.maintenance.plugin.traefik-maintenance.filename=/maintenance/under_maintenance.gif"
      - "traefik.http.middlewares.maintenance.plugin.traefik-maintenance.triggerFilename=/maintenance/under_maintenance.gif.trigger"
      - "traefik.http.middlewares.maintenance.plugin.traefik-maintenance.httpContentType=image/gif"
```
using json is also an option.

The way it works is:
1. Prepare the contents for the `filename` and leave it accessible to the traefik container. The contents of that file will be sent with the 503 error code. The content type of the 503 is also sent as configured.
2. Once the `triggerFilename` is present, the plugin will start sending the 503 error code. Removing the file will revert the behavior.
   The file is expected to be placed manually by an admin
   The new volume isn't strictly needed, but it's there to put the `triggerFilename` easier without entering in the container. The volume can be removed, but you'll need to enter the container to place those files.
3. Internal communication not going through traefik is expected to work normally. In particular, command line should still work without problems.

Additional notes:
* In case there are multiple containers exposed to the outside, it might be recommended to setup the same maintenance for all of them. This means that all communication coming from the outside would receive a 503 error.
* Internal communication is still possible as long as it doesn't go through traefik.
  * This means that, depending on the setup, it's possible for Collabora (or OnlyOffice) to save the file despite ocis being in maintenance mode. Note that this requires setup changes, so it won't be possible by default, and trying to save the file will cause an error under normal circumstances.
* As said, the new traefik's volume is for convenience. You can remove the volume, but you'll need to access the container to place the "maintenance file" and to switch on and off the maintenance mode.
* You can use any type of content for the 503 error. This could be used to show an "under maintenance" gif, which could also be used in the clients. However, there is no plan to do so.
  * Right now, the only requirement is that the page MUST return a 503 error, which is what we'll use to indicate the maintenance mode to the clients. It's expected that clients will ignore the content.

**Comment by jvillafanez** [comment]
I have a docker compose setup working, that's why I say it's possible.
```
  ocis:
    environment:
      STORAGE_USERS_GRPC_ADDR: "0.0.0.0:9157"
      STORAGE_USERS_HTTP_ADDR: "0.0.0.0:9158"
      STORAGE_USERS_DATA_SERVER_URL: "http://ocis:9158/data"
      STORAGE_USERS_DATA_GATEWAY_URL: "http://ocis:9200/data"
      STORAGE_USERS_EXPOSE_DATA_SERVER: true

  wopiserverco:
    environment:
      COLLABORATION_GRPC_ADDR: 0.0.0.0:9301
      COLLABORATION_HTTP_ADDR: 0.0.0.0:9300
      COLLABORATION_STORE_NODES: "ocis:9233"
      COLLABORATION_WOPI_SRC: http://wopiserverco:9300

  collabora:
    environment:
      aliasgroup2: http://wopiserverco:9300
```
That should be the relevant changes. I have a lot of "insecure" connections to make things easier, so not sure how relevant are those. I might also have missed additional configuration that could be required.

Now, maybe replicating the setup in kubernetes might be impossible or too difficult. It might be easier to consider every deployed service isolated in its own external host, so communication from service A to B would go through an external public network.

Taking into account that we'd require an internal private network (which docker can provide, but not sure about kubernetes), and the extra configuration (I'd rather keep as many default values as possible), I'm completely ok with skipping this setup from the docs.
In any case, I don't think the setup is very relevant because the general expectation is that Collabora won't work when the system is in maintenance mode. Probably any public-facing service should return a 503 error if maintenance mode is active.
