### ISSUE TITLE
webdav URL in file details is wrong

### ISSUE THREAD

**Issue by individual-it** [owncloud/web#11590]
## Describe the bug
The WebDAV URL in the file details mention the path `/dav/spaces/<space-id>` twice and by that makes the path invalid

## Steps to reproduce
1. enable 'Show WebDAV information in file details'  in personal settings
2. upload or create a file
3. check the WebDAV URL in the file details tab

## Expected behavior
`https://<ocis-host>/dav/spaces/<space-id>/New%20file.txt`

## Actual behavior
`/dav/spaces/<space-id>` is shown twice (first time unencoded).
e.g. `https://ocis.in-nepal.de/dav/spaces/e89c7a91-5166-4516-ba2b-c84cd130bf62$007f0f4e-cb0c-4d60-a229-180920aa97ec/dav/spaces/e89c7a91-5166-4516-ba2b-c84cd130bf62%24007f0f4e-cb0c-4d60-a229-180920aa97ec/New%20file.txt`

## Setup

oCIS: 6.4.0

<details>
<p>

```yaml
--

services:
  ocis:
    image: owncloud/ocis-rolling:${OCIS_DOCKER_TAG:-4.0.5}
    networks:
      ocis-net:
    ports:
      - "9200:9200"
    entrypoint:
      - /bin/sh
    command: ["-c", "ocis init || true; ocis server"]
    environment:
      OCIS_URL: https://${OCIS_DOMAIN:-ocis.in-nepal.de}
      OCIS_LOG_LEVEL: ${OCIS_LOG_LEVEL:-warn}
      OCIS_LOG_COLOR: "${OCIS_LOG_COLOR:-false}"
      OCIS_INSECURE: "${INSECURE:-false}"
      OCIS_SHARING_PUBLIC_SHARE_MUST_HAVE_PASSWORD: false
      PROXY_HTTP_ADDR: 0.0.0.0:9200
      PROXY_TLS: "false"
      OCIS_LOG_FILE: /var/log/ocis/ocis.log
      MICRO_REGISTRY_ADDRESS: 127.0.0.1:9233
      GATEWAY_GRPC_ADDR: 0.0.0.0:9142
      NATS_NATS_HOST: 0.0.0.0
      NATS_NATS_PORT: 9233
      OCIS_SERVICE_ACCOUNT_ID: ${OCIS_SERVICE_ACCOUNT_ID}
      OCIS_SERVICE_ACCOUNT_SECRET: ${OCIS_SERVICE_ACCOUNT_SECRET}
      WEB_OPTION_OPEN_LINKS_WITH_DEFAULT_APP: false
      WEB_UI_CONFIG_FILE: /etc/ocis/web.config.json
      WEB_ASSET_APPS_PATH: /var/lib/apps
      PROXY_CSP_CONFIG_FILE_LOCATION: /etc/ocis/csp.yaml
      COLLABORA_DOMAIN: ${COLLABORA_DOMAIN:-collabora.owncloud.test}
      ONLYOFFICE_DOMAIN: ${ONLYOFFICE_DOMAIN:-onlyoffice.owncloud.test}
        #THUMBNAILS_MAX_INPUT_IMAGE_FILE_SIZE: 2MB
    restart: always
    volumes:
      - type: bind
        source: ${OCIS_CONFIG_DIR}
        target: /etc/ocis
      - type: bind
        source: ${OCIS_DATA_DIR}
        target: /var/lib/ocis
      - type: bind
        source: ${WEB_ASSET_APPS_PATH}
        target: /var/lib/apps
```

</p>
</details>
