### ISSUE TITLE
Translations: Login UI  not  translations

### ISSUE THREAD

**Issue by hale177** [owncloud/web#12602]
### Describe the bug

my  local env  install version 7.1.2 also login dashboard was not translated. I am using the Chinese language, and my browser is Chrome with Chinese as the default language. 

However, the "username," "password," and "login" button remain in English instead of being translated into Chinese.  

so ，How to set the login UI to Chinese language ?

### Steps to reproduce

```textarea
1. set ocis web default chinese language 
2. quit and Login again
```

### Expected behavior

 login UI  display  chinese  language ( username / password / Log in)

### Actual behavior

![Image](https://github.com/user-attachments/assets/0225db04-e6d5-474d-881c-d6eb5a8a839c)

### Setup

```markdown
- Web version: 
- oCIS version: 7.1.2 (docker deploy)
- browser: chrome 133.0.6943.53(default chinese language)

### Additional context
```

docker-compose yaml 
```
services:
  ocis:
    image: owncloud/ocis:7.1.2
    container_name: ocis
    entrypoint: /bin/sh
    command: ['-c', 'ocis init --insecure yes || true && ocis server']
    ports:
      - 0.0.0.0:9200:9200/tcp
    volumes:
      - ./etc:/etc/ocis
      - ./data:/var/lib/ocis
      - /etc/localtime:/etc/localtime
    environment:
      OCIS_INSECURE: "true"
      PROXY_HTTP_ADDR: 0.0.0.0:9200
      OCIS_URL: https://192.168.6.240:9200
      OCIS_DEFAULT_LANGUAGE: zh
      PROXY_ENABLE_BASIC_AUTH: "true"
      IDM_ADMIN_PASSWORD: admin

```

_No response_
