### ISSUE TITLE
Infinite loading spinner after changing the OIDC client id

### ISSUE THREAD

**Issue by wkloucek** [owncloud/web#5612]
### Steps to reproduce
1. set following IDP configuration (identifier-registration.yaml) for oCIS
    ``` 
    ---
    # OpenID Connect client registry.
    clients:
    - id: web
      name: ownCloud web app
      trusted: yes
      redirect_uris:
        - https://localhost:9200/
        - https://localhost:9200/oidc-callback.html
        - https://localhost:9200/oidc-silent-redirect.html
      origins:
        - https://localhost:9200
    
    - id: web-1
      name: ownCloud web app
      trusted: yes
      redirect_uris:
        - https://localhost:9200/
        - https://localhost:9200/oidc-callback.html
        - https://localhost:9200/oidc-silent-redirect.html
      origins:
        - https://localhost:9200
    ```
1. start oCIS with `WEB_OIDC_CLIENT_ID=web`, open ownCloud Web and login
2. everything works fine
3. leave the browser / tab open
3. stop oCIS and start again with `WEB_OIDC_CLIENT_ID=web-1`, go to the tab, where Web is open and reload. Enjoy the infinite loading spinner.
5. open the exact same url in a new browser tab. Enjoy a functional ownCloud Web.

### Expected behaviour
In step 3 ownCloud Web should throw an error because the bearer token from the session storage is invalidated and then ask the IDP for a new bearer token and proceed like normal

### Actual behaviour
The loading spinner is displayed infinitely

### Background
oC Web takes some things in the session storage (only valid for the current tab):
![image](https://user-images.githubusercontent.com/34452982/127974568-3b3e7c0d-5af5-4116-8c19-f441af418f6e.png) 
The bearer token, which is kept in a non OIDC-client-id scoped storage is taken even after a change of the OIDC client id and therefore invalid.

Workaround-Patch:
```patch
diff --git a/packages/web-runtime/src/store/index.js b/packages/web-runtime/src/store/index.js
index b4fb7c1e..010cba66 100644
--- a/packages/web-runtime/src/store/index.js
+++ b/packages/web-runtime/src/store/index.js
@@ -19,7 +19,6 @@ const vuexPersistInSession = new VuexPersistence({
   reducer: state => {
     const { userReady, ...user } = state.user
     return {
-      user,
       router: state.router
     }
   }
```

As a sidenote: expired bearer tokens are correctly handled :+1:.
