### ISSUE TITLE
Public links asking for user and password (basic auth popup)

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#5727]
### Steps to reproduce
1. Create a password protected public link
2. Open the link

### Expected behaviour
A password field to open the public shared file or folder should appear.

### Actual behaviour
The site loads almost as expected, except that the browser asks for username and password. When pressing Cancel or the ESC key the prompt disappear and the regular public share password needs to be entered.

### Server configuration

**Operating system:** Ubuntu 18.04.5 LTS

**Web server:** apache 2.4.48

**Database:** mysql 5.7.35-0ubuntu0.18.04.1

**PHP version:** 7.4.21

**ownCloud version:** 10.8

**Updated from an older ownCloud or fresh install:** update from 10.7

**Where did you install ownCloud from:** oC tar

**Signing status (ownCloud 9.0 and above):** signed

**The content of config/config.php:**
```php
 {
        "system": {
            "updatechecker": false,
            "instanceid": "123123ocdabcd1234",
            "passwordsalt": "***REMOVED SENSITIVE VALUE***",
            "secret": "***REMOVED SENSITIVE VALUE***",
            "trusted_domains": [
                "cloud.myreallycooldomain.de"
            ],
            "datadirectory": "\/owncloudData",
            "overwrite.cli.url": "https:\/\/cloud.myreallycooldomain.de",
            "dbtype": "mysql",
            "version": "10.8.0.4",
            "dbname": "ocstraki",
            "dbhost": "localhost",
            "dbtableprefix": "oc_",
            "mysql.utf8mb4": true,
            "dbuser": "***REMOVED SENSITIVE VALUE***",
            "dbpassword": "***REMOVED SENSITIVE VALUE***",
            "logtimezone": "UTC",
            "installed": true,
            "ldapIgnoreNamingRules": false,
            "maintenance": false,
            "loglevel": 2,
            "trashbin_retention_obligation": "14,60",
            "mail_domain": "***REMOVED SENSITIVE VALUE***",
            "mail_from_address": "***REMOVED SENSITIVE VALUE***",
            "mail_smtpmode": "smtp",
            "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
            "mail_smtpport": "25",
            "mail_smtpauth": 1,
            "mail_smtpauthtype": "LOGIN",
            "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
            "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
            "mail_smtpdebug": true,
            "memcache.local": "\\OC\\Memcache\\APCu",
            "memcache.locking": "\\OC\\Memcache\\Redis",
            "redis": {
                "host": "localhost",
                "port": 6379,
                "timeout": 0
            },
            "web.baseUrl": "https:\/\/cloud.myreallycooldomain.de\/index.php\/apps\/web",
            "web.rewriteLinks": true
        }
    }
```

**List of activated apps:**
```yaml
      - activity:
        - Version: 2.6.1
        - Path: /var/www/owncloud/apps/activity
      - brute_force_protection:
        - Version: 1.1.0
        - Path: /var/www/owncloud/apps/brute_force_protection
      - comments:
        - Version: 0.3.0
        - Path: /var/www/owncloud/apps/comments
      - configreport:
        - Version: 0.2.0
        - Path: /var/www/owncloud/apps/configreport
      - dav:
        - Version: 0.6.0
        - Path: /var/www/owncloud/apps/dav
      - federatedfilesharing:
        - Version: 0.5.0
        - Path: /var/www/owncloud/apps/federatedfilesharing
      - federation:
        - Version: 0.1.0
        - Path: /var/www/owncloud/apps/federation
      - files:
        - Version: 1.5.2
        - Path: /var/www/owncloud/apps/files
      - files_external:
        - Version: 0.8.0
        - Path: /var/www/owncloud/apps/files_external
      - files_mediaviewer:
        - Version: 1.0.4
        - Path: /var/www/owncloud/apps/files_mediaviewer
      - files_pdfviewer:
        - Version: 0.12.2
        - Path: /var/www/owncloud/apps/files_pdfviewer
      - files_sharing:
        - Version: 0.14.0
        - Path: /var/www/owncloud/apps/files_sharing
      - files_trashbin:
        - Version: 0.9.1
        - Path: /var/www/owncloud/apps/files_trashbin
      - files_versions:
        - Version: 1.3.0
        - Path: /var/www/owncloud/apps/files_versions
      - firstrunwizard:
        - Version: 1.2.0
        - Path: /var/www/owncloud/apps/firstrunwizard
      - gallery:
        - Version: 16.1.1
        - Path: /var/www/owncloud/apps/gallery
      - market:
        - Version: 0.6.1
        - Path: /var/www/owncloud/apps/market
      - notifications:
        - Version: 0.5.4
        - Path: /var/www/owncloud/apps/notifications
      - oauth2:
        - Version: 0.4.4
        - Path: /var/www/owncloud/apps/oauth2
      - provisioning_api:
        - Version: 0.5.0
        - Path: /var/www/owncloud/apps/provisioning_api
      - systemtags:
        - Version: 0.3.0
        - Path: /var/www/owncloud/apps/systemtags
      - updatenotification:
        - Version: 0.2.1
        - Path: /var/www/owncloud/apps/updatenotification
      - web:
        - Version: 4.1.0
        - Path: /var/www/owncloud/apps/web
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration

**Browser:** Chrome/Firefox

**Operating system:** Windows 10

### Logs

**Web server access log** 
```
77.191.y.x - - [23/Aug/2021:11:37:43 +0200] "GET /index.php/apps/web/index.html HTTP/1.1" 200 7737 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"
77.191.y.x - - [23/Aug/2021:11:37:43 +0200] "GET /index.php/apps/web/css/web.css HTTP/1.1" 200 57206 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"
77.191.y.x - - [23/Aug/2021:11:37:43 +0200] "GET /index.php/apps/web/js/require.js HTTP/1.1" 200 27485 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"
77.191.y.x - - [23/Aug/2021:11:37:44 +0200] "GET /index.php/apps/web/js/web-runtime-b515b27d.js HTTP/1.1" 200 21252 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"
77.191.y.x - - [23/Aug/2021:11:37:44 +0200] "GET /index.php/apps/web/js/_chunks/encodePath-5ef8ca06.js HTTP/1.1" 200 1042 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"
77.191.y.x - - [23/Aug/2021:11:37:44 +0200] "GET /index.php/apps/web/js/_chunks/vendor-f81f7dc8.js HTTP/1.1" 200 728990 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"
77.191.y.x - - [23/Aug/2021:11:37:45 +0200] "GET /index.php/apps/web/config.json HTTP/1.1" 200 1512 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"
77.191.y.x - - [23/Aug/2021:11:37:45 +0200] "GET /index.php/apps/web/js/web-app-files-6d67c5ba.js HTTP/1.1" 200 51441 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"
77.191.y.x - - [23/Aug/2021:11:37:46 +0200] "GET /index.php/apps/web/js/_chunks/resources-57c772cc.js HTTP/1.1" 200 17842 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"
77.191.y.x - - [23/Aug/2021:11:37:46 +0200] "GET /index.php/apps/web/js/_chunks/index-a80cece2.js HTTP/1.1" 200 1138 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"
77.191.y.x - - [23/Aug/2021:11:37:46 +0200] "GET /index.php/apps/web/js/_chunks/constants-28c72d8d.js HTTP/1.1" 200 6841 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"
77.191.y.x - - [23/Aug/2021:11:37:46 +0200] "GET /index.php/apps/web/js/web-app-media-viewer-3ff4dc5f.js HTTP/1.1" 200 4435 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"
77.191.y.x - - [23/Aug/2021:11:37:46 +0200] "GET /index.php/apps/web/js/web-app-draw-io-e1aba242.js HTTP/1.1" 200 2835 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"
77.191.y.x - - [23/Aug/2021:11:37:46 +0200] "GET /index.php/apps/web/themes/owncloud/assets/logo.svg HTTP/1.1" 200 10756 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"
77.191.y.x - - [23/Aug/2021:11:37:46 +0200] "GET /index.php/apps/web/themes/owncloud/assets/loginBackground.jpg HTTP/1.1" 200 89015 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"
77.191.y.x - - [23/Aug/2021:11:37:46 +0200] "PROPFIND /remote.php/dav/public-files/9JjbkipaAphsgfh HTTP/1.1" 401 1414 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"
77.191.y.x - test [23/Aug/2021:11:37:56 +0200] "PROPFIND /remote.php/dav/public-files/9JjbkipaAphsgfh HTTP/1.1" 401 6548 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"
```

**Web server error log**
```
[Mon Aug 23 11:03:28.341555 2021] [mpm_prefork:notice] [pid 2378] AH00171: Graceful restart requested, doing restart
[Mon Aug 23 11:03:28.563153 2021] [mpm_prefork:notice] [pid 2378] AH00163: Apache/2.4.48 (Ubuntu) OpenSSL/1.1.1 configured -- resuming normal operations
[Mon Aug 23 11:03:28.563177 2021] [core:notice] [pid 2378] AH00094: Command line: '/usr/sbin/apache2'
[Mon Aug 23 11:15:02.077791 2021] [mpm_prefork:notice] [pid 2378] AH00171: Graceful restart requested, doing restart
[Mon Aug 23 11:15:02.176091 2021] [mpm_prefork:notice] [pid 2378] AH00163: Apache/2.4.48 (Ubuntu) OpenSSL/1.1.1 configured -- resuming normal operations
[Mon Aug 23 11:15:02.176110 2021] [core:notice] [pid 2378] AH00094: Command line: '/usr/sbin/apache2'
```

**ownCloud log (data/owncloud.log)**
```
   {"reqId":"7rKR4f2FspfgUHKof144","level":2,"time":"2021-08-23T09:12:08+00:00","remoteAddr":"77.191.y.x","user":"--","app":"core","method":"PROPFIND","url":"\/remote.php\/dav\/public-files\/9JjbkipaAphsgfh","message":"Login failed: 'fvsdfsdfsdfsd' (Remote IP: '77.191.y.x')"}
    {"reqId":"TvrIvBVA5FdlEMPlLfpz","level":2,"time":"2021-08-23T09:12:12+00:00","remoteAddr":"77.191.y.x","user":"--","app":"core","method":"PROPFIND","url":"\/remote.php\/dav\/public-files\/9JjbkipaAphsgfh","message":"Login failed: 'public' (Remote IP: '77.191.y.x')"}
```

### Ticket origin
https://central.owncloud.org/t/public-links-asking-for-user-and-password/33666
As soon as resolved, post solution in central. Same for further questions regarding this ticket.
