### ISSUE TITLE
White screen 

### ISSUE THREAD

**Issue by anthony-launay** [owncloud/web#5745]
### Steps to reproduce
1. Update to 10.8.0.4
2. Click on "New design" button 
3. OpenID Connect is not activated

### Expected behaviour
I should see the new theme

### Actual behaviour
I don't see the new theme but white screen. 

### Server configuration
**Operating system**: Linux (Debian)

**Web server:** Apache 2.4.25 

**Database:** Mysql

**PHP version:** 7.2.34

**ownCloud version:** 10.8.0.4

**Where did you install ownCloud from:** Updater

**Signing status (ownCloud 9.0 and above):** True

** The content of config/config.php:

```
"config": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "cors.allowed-domains": [],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "crashdirectory": "\/var\/www\/owncloud\/data",
        "version": "10.8.0.4",
        "version.hide": false,
        "show_server_hostname": false,
        "use_relative_domain_name": false,
        "dbtype": "l",
        "dbhost": "localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_language": "fr_FR",
        "enable_avatars": true,
        "allow_user_to_change_display_name": false,
        "remember_login_cookie_lifetime": 1296000,
        "session_lifetime": 1200,
        "session_keepalive": true,
        "token_auth_enforced": false,
        "strict_login_enforced": false,
        "login.alternatives": [],
        "csrf.disabled": false,
        "http.cookie.samesite": "Strict",
        "skeletondirectory": "\/home\/owncloud\/core\/skeleton",
        "user_backends": [],
        "lost_password_link": "disabled",
        "accounts.enable_medial_search": true,
        "groups.enable_medial_search": true,
        "user.search_min_length": 2,
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpdebug": false,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": 587,
        "mail_smtptimeout": 10,
        "mail_smtpsecure": "",
        "mail_smtpauth": true,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "overwritehost": "",
        "overwriteprotocol": "",
        "overwritewebroot": "",
        "overwritecondaddr": "",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "web.baseUrl": "***REMOVED SENSITIVE VALUE***\/index.php\/apps\/web",
        "web.rewriteLinks": true,
        "htaccess.RewriteBase": "\/",
        "proxy": "",
        "proxyuserpwd": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "disabled",
        "trashbin_purge_limit": 50,
        "trashbin_skip_directories": [
            "temp"
        ],
        "trashbin_skip_extensions": [
            "iso",
            "mkv"
        ],
        "trashbin_skip_size_threshold": "1GB",
        "versions_retention_obligation": "auto",
        "updatechecker": true,
        "updater.server.url": "https:\/\/updates.owncloud.com\/server\/",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "has_internet_connection": true,
        "check_for_working_wellknown_setup": true,
        "config_is_read_only": false,
        "operation.mode": "single-instance",
        "log_type": "owncloud",
        "logfile": "\/var\/log\/owncloud.log",
        "loglevel": 2,
        "syslog_tag": "ownCloud",
        "log.syslog.format": "[%reqId%][%remoteAddr%][%user%][%app%][%method%][%url%] %message%",
        "logdateformat": "F d, Y H:i:s",
        "logtimezone": "Europe\/Paris",
        "cron_log": true,
        "log_rotate_size": 104857600,
        "apps_paths": [
            {
                "path": "\/home\/owncloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/home\/owncloud\/apps-external",
                "url": "\/apps-external",
                "writable": true
            }
        ],
        "enable_previews": true,
        "previews_path": "",
        "preview_max_x": 2048,
        "preview_max_y": 2048,
        "preview_max_scale_factor": 10,
        "preview_max_filesize_image": 50,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "preview_office_cl_parameters": "--headless --nologo --nofirststartwizard --invisible --norestore ",
        "0": "--convert-to pdf --outdir ",
        "enabledPreviewProviders": [
            "OC\\Preview\\PDF",
            "OC\\Preview\\SGI",
            "OC\\Preview\\Heic",
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown"
        ],
        "comments.managerFactory": "\\OC\\Comments\\ManagerFactory",
        "systemtags.managerFactory": "\\OC\\SystemTag\\ManagerFactory",
        "maintenance": false,
        "singleuser": false,
        "enable_certificate_management": false,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***",
            "dbindex": 0
        },
        "cache_path": "",
        "cache_chunk_gc_ttl": 86400,
        "dav.chunk_base_dir": "",
        "sharing.managerFactory": "\\OC\\Share20\\ProviderFactory",
        "sharing.federation.allowHttpFallback": false,
        "dbdriveroptions": {
            "1002": "SET wait_timeout = 28800"
        },
        "sqlite.journal_mode": "DELETE",
        "mysql.utf8mb4": false,
        "db.platform": false,
        "supportedDatabases": [
            "sqlite",
            "mysql",
            "pgsql",
            "oci"
        ],
        "tempdirectory": "\/home\/owncloud\/data\/tmp",
        "hashingCost": 10,
        "blacklisted_files": [
            ".htaccess"
        ],
        "blacklisted_files_regex": [
            ".*\\.ext",
            "^somefilename.*"
        ],
        "excluded_directories": [
            ".snapshot",
            "~snapshot"
        ],
        "excluded_directories_regex": [
            "^backup.*",
            ".*backup$"
        ],
        "integrity.excluded.files": [
            ".DS_Store",
            "Thumbs.db",
            ".directory",
            ".webapp",
            ".htaccess",
            ".user.ini"
        ],
        "integrity.ignore.missing.app.signature": [
            "app-id of app-1",
            "app-id of theme-2"
        ],
        "share_folder": "\/",
        "cipher": "AES-256-CFB",
        "encryption.use_legacy_encoding": false,
        "minimum.supported.desktop.version": "2.3.3",
        "quota_include_external_storage": false,
        "filesystem_check_changes": 0,
        "filesystem.max_mountpoint_move_attempts": 10,
        "part_file_in_storage": true,
        "filesystem_cache_readonly": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_proxies": [],
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED",
            "HTTP_FORWARDED_FOR"
        ],
        "max_filesize_animated_gifs_public_sharing": 10,
        "filelocking.enabled": true,
        "filelocking.ttl": 3600,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "upgrade.disable-web": false,
        "upgrade.automatic-app-update": true,
        "debug": false,
        "data-fingerprint": "",
        "files_external_allow_create_new_local": false,
        "smb.logging.enable": false,
        "dav.enable.async": false,
        "grace_period.demo_key.show_popup": false,
        "grace_period.demo_key.link": "https:\/\/owncloud.com\/try-enterprise\/"
    },
```

**List of activated apps:**

```
Enabled:
  - activity:
    - Version: 2.6.1
    - Path: /home/owncloud/apps-external/activity
  - comments:
    - Version: 0.3.0
    - Path: /home/owncloud/apps/comments
  - configreport:
    - Version: 0.2.0
    - Path: /home/owncloud/apps/configreport
  - customgroups:
    - Version: 0.6.2
    - Path: /home/owncloud/apps/customgroups
  - dav:
    - Version: 0.6.0
    - Path: /home/owncloud/apps/dav
  - federatedfilesharing:
    - Version: 0.5.0
    - Path: /home/owncloud/apps/federatedfilesharing
  - federation:
    - Version: 0.1.0
    - Path: /home/owncloud/apps/federation
  - files:
    - Version: 1.5.2
    - Path: /home/owncloud/apps/files
  - files_external:
    - Version: 0.8.0
    - Path: /home/owncloud/apps/files_external
  - files_mediaviewer:
    - Version: 1.0.4
    - Path: /home/owncloud/apps/files_mediaviewer
  - files_sharing:
    - Version: 0.14.0
    - Path: /home/owncloud/apps/files_sharing
  - files_trashbin:
    - Version: 0.9.1
    - Path: /home/owncloud/apps/files_trashbin
  - files_versions:
    - Version: 1.3.0
    - Path: /home/owncloud/apps/files_versions
  - files_videoplayer:
    - Version: 0.9.9
    - Path: /home/owncloud/apps/files_videoplayer
  - firstrunwizard:
    - Version: 1.2.0
    - Path: /home/owncloud/apps/firstrunwizard
  - market:
    - Version: 0.6.1
    - Path: /home/owncloud/apps/market
  - notifications:
    - Version: 0.5.4
    - Path: /home/owncloud/apps/notifications
  - oauth2:
    - Version: 0.4.4
    - Path: /home/owncloud/apps/oauth2
  - provisioning_api:
    - Version: 0.5.0
    - Path: /home/owncloud/apps/provisioning_api
  - systemtags:
    - Version: 0.3.0
    - Path: /home/owncloud/apps/systemtags
  - updatenotification:
    - Version: 0.2.1
    - Path: /home/owncloud/apps/updatenotification
  - web:
    - Version: 4.1.0
    - Path: /home/owncloud/apps-external/web
Disabled:
  - encryption:
    - Path: /home/owncloud/apps/encryption
  - external:
    - Path: /home/owncloud/apps/external
  - user_external:
    - Path: /home/owncloud/apps/user_external
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chrome / Firefox

**Operating system:** Linux (Ubuntu)

#### Browser log

Chrome : 
![image](https://user-images.githubusercontent.com/3624359/131115192-71a46183-83a7-4e1b-8ebb-19395116d679.png)

Firefox : 
![image](https://user-images.githubusercontent.com/3624359/131115398-b8f2f355-b82e-4d35-8a38-ca653ecfc683.png)
