### ISSUE TITLE
Contents of text document lost on automatic logout procedure (no auto-save)

### ISSUE THREAD

**Issue by TheRealBro** [owncloud/web#8546]
### Steps to reproduce
1. Create a new text document in ownCloud Web
2. Open document with text editor
3. Enter some content
4. Wait until you get logged out by automatic logout procedure

### Expected behaviour
Document should auto-save text and contain the text I added before automatic logout happened

### Actual behaviour
Document is empty, no auto-save, all contents are lost

### Environment general
**Operating system**: n/a happens in Firefox, but I guess browser does not matter

**Backend (ownCloud Core or Infinite Scale)**: ownCloud Core

**Are you using an external user-backend, if yes which one:** LDAP + SSO with Keycloak

### Environment ownCloud Core
**Web server:** 
```
# apache2 -v
Server version: Apache/2.4.54 (Ubuntu)
Server built:   2022-06-08T15:58:53
```
from http://ppa.launchpad.net/ondrej/apache2/ubuntu

**Database:**
```
 # mariadb --version
mariadb  Ver 15.1 Distrib 10.1.48-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
```

**PHP version:**
```
 # php --version
PHP 7.4.33 (cli) (built: Nov  8 2022 11:33:17) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.33, Copyright (c), by Zend Technologies
```
from http://ppa.launchpad.net/ondrej/php/ubuntu

**Version:** 
```
# occ --version
ownCloud 10.11.0
```

**Updated from an older ownCloud**

**Where did you install ownCloud from:** tarball

**Signing status (ownCloud 9.0 and above):** 
```
 # occ integrity:check-core --verbose -V
ownCloud 10.11.0

No errors have been found.
```

ownCloud Web runs from docker container
```
owncloud/web:6.0.0
```
from https://hub.docker.com/r/owncloud/web

**The content of config/config.php:** n/a or ask

**List of activated apps:**

```
# occ app:list
Enabled:
  - activity:
    - Version: 2.7.1
    - Path: /var/www/owncloud/apps/activity
  - admin_audit:
    - Version: 2.1.3
    - Path: /var/www/owncloud/apps/admin_audit
  - comments:
    - Version: 0.3.0
    - Path: /var/www/owncloud/apps/comments
  - configreport:
    - Version: 0.2.1
    - Path: /var/www/owncloud/apps/configreport
  - contacts:
    - Version: 1.5.5
    - Path: /usr/local/src/owncloud/custom/contacts
  - dav:
    - Version: 0.7.0
    - Path: /var/www/owncloud/apps/dav
  - drawio:
    - Version: 0.0.9
    - Path: /usr/local/src/owncloud/custom/drawio
  - external:
    - Version: 1.4.0
    - Path: /var/www/owncloud/apps/external
  - federatedfilesharing:
    - Version: 0.5.0
    - Path: /var/www/owncloud/apps/federatedfilesharing
  - federation:
    - Version: 0.1.0
    - Path: /var/www/owncloud/apps/federation
  - files:
    - Version: 1.5.2
    - Path: /var/www/owncloud/apps/files
  - files_external:
    - Version: 0.9.0
    - Path: /var/www/owncloud/apps/files_external
  - files_mediaviewer:
    - Version: 1.0.5
    - Path: /var/www/owncloud/apps/files_mediaviewer
  - files_pdfviewer:
    - Version: 1.0.1
    - Path: /var/www/owncloud/apps/files_pdfviewer
  - files_sharing:
    - Version: 0.14.0
    - Path: /var/www/owncloud/apps/files_sharing
  - files_texteditor:
    - Version: 2.4.1
    - Path: /var/www/owncloud/apps/files_texteditor
  - files_trashbin:
    - Version: 0.9.1
    - Path: /var/www/owncloud/apps/files_trashbin
  - files_versions:
    - Version: 1.3.0
    - Path: /var/www/owncloud/apps/files_versions
  - firstrunwizard:
    - Version: 1.2.0
    - Path: /var/www/owncloud/apps/firstrunwizard
  - guests:
    - Version: 0.12.2
    - Path: /usr/local/src/owncloud/custom/guests
  - impersonate:
    - Version: 0.5.2
    - Path: /usr/local/src/owncloud/custom/impersonate
  - market:
    - Version: 0.7.0
    - Path: /var/www/owncloud/apps/market
  - notifications:
    - Version: 0.5.4
    - Path: /var/www/owncloud/apps/notifications
  - oauth2:
    - Version: 0.5.3
    - Path: /var/www/owncloud/apps/oauth2
  - onlyoffice:
    - Version: 7.6.7
    - Path: /usr/local/src/owncloud/custom/onlyoffice
  - provisioning_api:
    - Version: 0.5.0
    - Path: /var/www/owncloud/apps/provisioning_api
  - richdocuments:
    - Version: 3.0.0
    - Path: /usr/local/src/owncloud/custom/richdocuments
  - search_elastic:
    - Version: 2.2.0
    - Path: /usr/local/src/owncloud/custom/search_elastic
  - sentry:
    - Version: 0.1.0
    - Path: /usr/local/src/owncloud/custom/sentry
  - systemtags:
    - Version: 0.3.0
    - Path: /var/www/owncloud/apps/systemtags
  - templateeditor:
    - Version: 0.4.0
    - Path: /var/www/owncloud/apps/templateeditor
  - theme-enterprise:
    - Version: 2.3.1
    - Path: /var/www/owncloud/apps/theme-enterprise
  - twofactor_totp:
    - Version: 0.7.4
    - Path: /usr/local/src/owncloud/custom/twofactor_totp
  - web:
    - Version: 6.0.0
    - Path: /usr/local/src/owncloud/custom/web
  - windows_network_drive:
    - Version: 2.1.1
    - Path: /var/www/owncloud/apps/windows_network_drive
  - wopi:
    - Version: 1.6.1
    - Path: /usr/local/src/owncloud/custom/wopi
  - workflow:
    - Version: 0.5.4
    - Path: /var/www/owncloud/apps/workflow
```

**Are you using external storage, if yes which one:** local, xfs

**Are you using encryption:** no

### Client configuration
**Browser:** Firefox 110.0.1 (64-Bit)

**Operating system:** Ubuntu Linux

#### Web server error log
```
n/a or ask
```

#### ownCloud log (data/owncloud.log)
```
n/a or ask
```

#### Browser log
```
n/a or ask
```
