### ISSUE TITLE
Uploading an entire folder over the Web Interface freezes the frontend

### ISSUE THREAD

**Issue by marciofeld** [owncloud/web#9817]
## Describe the bug

After dragging or choosing a local folder with lots of files to the Infinite Scale Web Interface to be uploaded, the frontend freezes. Sometimes, after waiting a big amount of minutes, it unfreezes the frontend and starts uploading the files, but most of the time it fails the upload.

![image](https://github.com/owncloud/ocis/assets/85581321/b315ec36-768a-493a-8285-90e8c7ecf2a6)

## Steps to reproduce

1. Log in to Infinite Scale using the Web Browser
2. Drag a local folder with lots of files and subfolders to your personal folder

## Expected behavior
The web frontend freezes. The browser may report it as an Unresponsive Page.

## Actual behavior
There are no server logs generated or frontend logs. When opening the browser task manager, it shows the Infinite Scale Tab Task consuming a large amount of memory.
No outbound network traffic was reported from the client or inbound network traffic to the server.

## Setup

Infinite Scale version 4.0.2 Docker Container running in a M5.Large AWS EC2 Instance, using AWS S3 Bucket as storage.
Using AWS ALB (Application Load Balancer) as the Reverse Proxy.

Please find the `docker-compose.yml` file below:

<details>
<p>

```
version: "3.7"

services:
  ocis:
    image: owncloud/ocis:4.0.2
    entrypoint:
      - /bin/sh
    # run ocis init to initialize a configuration file with random secrets
    # it will fail on subsequent runs, because the config file already exists
    # therefore we ignore the error and then start the ocis server
    command: ["-c", "ocis init || true; ocis server"]
    environment:
      OCIS_URL: <MY INFINITE SCALE URL>
      OCIS_LOG_LEVEL: "info"
      OCIS_LOG_COLOR: "false"
      PROXY_TLS: "false" # do not use SSL between Traefik and oCIS
      # activate s3ng storage driver
      STORAGE_USERS_DRIVER: s3ng
      STORAGE_SYSTEM_DRIVER: ocis # keep system data on ocis storage since this are only small files atm
      # s3ng specific settings
      STORAGE_USERS_S3NG_ENDPOINT: "<MY S3 ENDPOINT>"
      STORAGE_USERS_S3NG_REGION: "<MY AWS REGION>"
      STORAGE_USERS_S3NG_ACCESS_KEY: ${S3_ACCESS_KEY}
      STORAGE_USERS_S3NG_SECRET_KEY: ${S3_SECRET_KEY}
      STORAGE_USERS_S3NG_BUCKET: "<MY S3 BUCKET NAME>"
      # INSECURE: needed if oCIS / Traefik is using self generated certificates
      OCIS_INSECURE: "false"
      # basic auth (not recommended, but needed for eg. WebDav clients that do not support OpenID Connect)
      PROXY_ENABLE_BASIC_AUTH: "false"
      # admin user password
      IDM_ADMIN_PASSWORD: "admin" # this overrides the admin password from the configuration file
      # demo users
      IDM_CREATE_DEMO_USERS: "false"
    volumes:
      - ocis-config:/etc/ocis
      - ocis-data:/var/lib/ocis
    restart: always
    ports:
      - "9200:9200"

volumes:
  ocis-config:
  ocis-data:
```

</p>
</details>
